[versions]
alchemist = "13.0.6"
kotlin = "1.6.10"

[libraries]
alchemist = { module = "it.unibo.alchemist:alchemist", version.ref = "alchemist" }
alchemist-protelis = { module = "it.unibo.alchemist:alchemist-incarnation-protelis", version.ref = "alchemist" }
alchemist-swingui = { module = "it.unibo.alchemist:alchemist-swingui", version.ref = "alchemist" }
alchemist-scafi = { module = "it.unibo.alchemist:alchemist-incarnation-scafi", version.ref = "alchemist" }
protelis-interpreter = "org.protelis:protelis-interpreter:15.2.2"

[bundles]
alchemist-protelis = [ "alchemist", "alchemist-protelis", "protelis-interpreter", "alchemist-swingui" ]

[plugins]
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "0.3.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = { id = "org.danilopianini.gradle-kotlin-qa", version = "0.14.1" }
multiJvmTesting = { id = "org.danilopianini.multi-jvm-test-plugin", version = "0.3.4" }
taskTree = { id = "com.dorongold.task-tree", version = "2.1.0" }
